### PR TITLE
Fix minor bugs for add task command regarding some date time issue

### LINKED ISSUE #200: Add_task wrong error message
Input; add_task n/task1 d/2021-01-01 p/2 t/tag1 c/cat1
Expected outcome: an error message stating the date given is not allowed
Actual outcome: an error message saying event start date and end date are past
image

@YuFeng0930 @ljhgab this issue may be linked to #201

### LINKED ISSUE #201: add_task does not allow deadline of today
Input: add_task n/task1 d/2021-03-29 p/2 t/tag1 c/cat1
Expected outcome: a new task being added with the deadline of 2021-03-29, which is the date of (today)
Actual outcome: not allowed as date is seen as past.

I think this should be allowed as the deadline is today, not yesterday.

@YuFeng0930 @ljhgab this may be linked to #200

### PR DESCRIPTION
**Pull request by ljhgabe**
close #200
close #201

### CODE REVIEW

**Comment by litone01** [comment]
need to write as close #200 close #201 haha otherwise it only closes 200

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 1]
```diff
@@ -11,7 +11,7 @@
     public static final String MESSAGE_INVALID_TASK_DISPLAYED_INDEX = "The task index provided is invalid";
     public static final String MESSAGE_EVENTS_LISTED_OVERVIEW = "%1$d events listed!";
     public static final String MESSAGE_PAST_EVENT_END_DATE_TIME = "The event end date and end time provided are past";
-    public static final String MESSAGE_PAST_EVENT_DEADLINE = "The task deadline provided is past";
+    public static final String MESSAGE_PAST_DEADLINE = "The task deadline provided is past";
```
Comment (litone01) [inline src/main/java/seedu/address/commons/core/Messages.java]: can we rephrase the message to "Please ensure the deadline provided is not earlier than today. This means only today and date later than today are allowed." or something similar haha @SoulUseless a better suggestion? same for the error message for event because the original message sounds a bit wrong hmmm

File: src/main/java/seedu/address/model/common/DatePastPredicate.java [hunk 2]
```diff
@@ -13,7 +13,7 @@ public DatePastPredicate() { }
 
     @Override
     public boolean test(Date date) {
-        return nowDate.isBefore(date.getDate());
+        return nowDate.isBefore(date.getDate()) || nowDate.isEqual(date.getDate());
```
Comment (litone01) [inline src/main/java/seedu/address/model/common/DatePastPredicate.java:16]: wait ah I think we are trying to allow today to be added? like today is 2021-03-29, it should be allowed as a deadline?

**Review by litone01 — CHANGES_REQUESTED** [review]

**Review by litone01 — APPROVED** [review]
